apiVersion: v1
kind: Secret
metadata:
  name: drone
  labels:
    app: drone
type: Opaque
data:
  secret: "eno1ZFJnc0FSVFJ4S0d2T3FlTmZYclow" # this HAS to be base64 encoded, e.g.: openssl rand 1024 | tr -dc 'a-zA-Z0-9' | head -c24 | base64
